### ISSUE TITLE
Unable to get sample  size calculations for continuous outcomes with normal distribution 

### ISSUE THREAD

**Issue by VenkataGanesh89** [tobiasmuetze/ThreeArmedTrials#3]
The following code gives the same error for any values entered in the exp, ref and pla arms
```
power_RET(experiment= c(112.9,5), reference= c(105,5), placebo= c(113.2,5), 
          Delta=0.6, sig_level=0.025, power=0.8, n=NULL, 
          allocation = c(1/3, 1/3, 1/3), var_estimation = "RML", 
          distribution = "normal")
```
Error in calc_power_ret.normal(x = x, Delta = Delta, allocation = w, n = n,  : 
  Parameter vector is not located in the alternative.

**Comment by tobiasmuetze** [comment]
Please note that the R package `ThreeArmedTrials` considers smaller means to be favorable; see the [vignette ](https://cran.r-project.org/web/packages/ThreeArmedTrials/vignettes/ThreeArmedTrials.html)for details. In your code, it seems that larger means are favorable. A workaround is to consider negative values:


    power_RET(experiment= c(-112.9,5), reference= c(-105,5), placebo= c(-113.2,5), 
              Delta=0.6, sig_level=0.025, power=0.8, n=NULL, 
              allocation = c(1/3, 1/3, 1/3), var_estimation = "RML", 
              distribution = "normal")
